# ============================================================================
# HQ_2p1d_BG_generated.jl -- GENERATED by Julia/tools/derive_hq_2p1d.wls.  DO NOT EDIT.
#
# The charm first moment phi = (alpha, nu^x, nu^y) on a PRESCRIBED 2+1D background,
# Milne (tau, x, y, eta_s), boost invariant, metric diag(-1, 1, 1, tau^2):
#     Nabla_mu (n u^mu + nu^mu) = 0
#     tau_n Delta^mu_b D nu^b + nu^mu + kappa Delta^{mu b} d_b alpha = 0
# in the source-on-the-LHS convention  A_t d_tau phi + A_x d_x phi + A_y d_y phi + src = 0,
# the convention of every matrix in this directory.
#
# The same generator reproduces Fluidum's shipped 1-D cylindrical HQ_const_BG matrix
# entry by entry (gate G4), which is why this chart is trusted.
# ============================================================================

"""
    hq2d_matrices(al, nuxF, nuyF, tau, T, ux, uy, dtT, dxT, dyT,
                  dtux, dxux, dyux, dtuy, dxuy, dyuy, n, dn_dT, dn_da, taun, kappa)

(A_t, A_x, A_y, src) for the 2+1D charm first moment on a prescribed background.
"""
function hq2d_matrices(al, nuxF, nuyF, tau, T, ux, uy, dtT, dxT, dyT,
                       dtux, dxux, dyux, dtuy, dxuy, dyuy,
                       n, dn_dT, dn_da, taun, kappa)
    At = SMatrix{3,3}((
        sqrt(1 + ux^2 + uy^2)*(dn_da),
        kappa*ux*sqrt(1 + ux^2 + uy^2),
        kappa*uy*sqrt(1 + ux^2 + uy^2),
        ux/sqrt(1 + ux^2 + uy^2),
        taun*sqrt(1 + ux^2 + uy^2),
        0,
        uy/sqrt(1 + ux^2 + uy^2),
        0,
        taun*sqrt(1 + ux^2 + uy^2)))

    Ax = SMatrix{3,3}((
        ux*(dn_da),
        kappa*(1 + ux^2),
        kappa*ux*uy,
        1,
        taun*ux,
        0,
        0,
        0,
        taun*ux))

    Ay = SMatrix{3,3}((
        uy*(dn_da),
        kappa*ux*uy,
        kappa*(1 + uy^2),
        0,
        taun*uy,
        0,
        1,
        0,
        taun*uy))

    src = SVector{3}((
        (-(dtux*nuxF*tau*ux^2) - dtuy*nuxF*tau*ux*uy - dtux*nuyF*tau*ux*uy - dtuy*nuyF*tau*uy^2 + dtux*nuxF*tau*(1 + ux^2 + uy^2) + dtuy*nuyF*tau*(1 + ux^2 + uy^2) + nuxF*ux*(1 + ux^2 + uy^2) + dtux*n*tau*ux*(1 + ux^2 + uy^2) + nuyF*uy*(1 + ux^2 + uy^2) + dtuy*n*tau*uy*(1 + ux^2 + uy^2) + dxux*n*tau*(1 + ux^2 + uy^2)^(3/2) + dyuy*n*tau*(1 + ux^2 + uy^2)^(3/2) + n*(1 + ux^2 + uy^2)^2 + dxT*tau*ux*(1 + ux^2 + uy^2)^(3/2)*(dn_dT) + dyT*tau*uy*(1 + ux^2 + uy^2)^(3/2)*(dn_dT) + dtT*tau*(1 + ux^2 + uy^2)^2*(dn_dT))/(tau*(1 + ux^2 + uy^2)^(3/2)),
        (nuxF*(1 + dxuy*taun*ux^3*uy + uy^2 - taun*ux*(1 + uy^2)*(dyux*uy + dtux*sqrt(1 + ux^2 + uy^2)) + ux^2*(1 + dyuy*taun*uy^2 - dxux*taun*(1 + uy^2) + dtuy*taun*uy*sqrt(1 + ux^2 + uy^2))) - nuyF*taun*ux*(dxuy*ux^3 + dyuy*uy + dtuy*sqrt(1 + ux^2 + uy^2) + ux^2*(-(dxux*uy) + dyuy*uy + dtuy*sqrt(1 + ux^2 + uy^2)) + ux*(dxuy - uy*(dyux*uy + dtux*sqrt(1 + ux^2 + uy^2)))))/(1 + ux^2 + uy^2),
        (nuyF*(1 - dxuy*taun*ux^3*uy + (1 - dyuy*taun)*uy^2 - dtuy*taun*uy*sqrt(1 + ux^2 + uy^2) + ux^2*(1 + (dxux - dyuy)*taun*uy^2 - dtuy*taun*uy*sqrt(1 + ux^2 + uy^2)) + taun*ux*uy*(-dxuy + uy*(dyux*uy + dtux*sqrt(1 + ux^2 + uy^2)))) - nuxF*taun*uy*(dxux*ux + dyux*uy^3 + dtux*sqrt(1 + ux^2 + uy^2) + uy^2*(dxux*ux - dyuy*ux + dtux*sqrt(1 + ux^2 + uy^2)) + uy*(dyux - ux*(dxuy*ux + dtuy*sqrt(1 + ux^2 + uy^2)))))/(1 + ux^2 + uy^2)))

    return (At, Ax, Ay, src)
end


"""
    hq2d_live_rows(al, nuxF, nuyF, tau, T, ux, uy, n, dn_dT, dn_da, taun, kappa)

The SAME three charm equations with the medium promoted from background to FIELDS: the returned
3x6 blocks are the coefficients of d(T, u^x, u^y, alpha, nu^x, nu^y), in that column order, and
`src` is what is left over.  Columns 4:6 are exactly the background-mode 3x3 matrices, and putting
columns 1:3 back onto the background derivatives recovers the background-mode source (gates G6a/G6b
of derive_hq_2p1d.wls) -- the two forms are one system, sorted two ways.

Used by `matrix2d_visc_HQ_BG!` to fill rows 8:10 of the 10-field live solver, whose columns are
(T, ux, uy, piyy, pizz, pixy, piB, alpha, nu^x, nu^y): the six columns land at 1,2,3,8,9,10.
"""
function hq2d_live_rows(al, nuxF, nuyF, tau, T, ux, uy, n, dn_dT, dn_da, taun, kappa)
    AtL = SMatrix{3,6}((
        sqrt(1 + ux^2 + uy^2)*(dn_dT),
        0,
        0,
        (-(nuyF*ux*uy) + nuxF*(1 + uy^2) + n*ux*(1 + ux^2 + uy^2))/(1 + ux^2 + uy^2)^(3/2),
        (taun*ux*(nuyF*ux*uy - nuxF*(1 + uy^2)))/sqrt(1 + ux^2 + uy^2),
        -((taun*uy*(nuxF - nuyF*ux*uy + nuxF*uy^2))/sqrt(1 + ux^2 + uy^2)),
        (nuyF*(1 + ux^2) - nuxF*ux*uy + n*uy*(1 + ux^2 + uy^2))/(1 + ux^2 + uy^2)^(3/2),
        -((taun*ux*(nuyF + nuyF*ux^2 - nuxF*ux*uy))/sqrt(1 + ux^2 + uy^2)),
        (taun*uy*(-(nuyF*(1 + ux^2)) + nuxF*ux*uy))/sqrt(1 + ux^2 + uy^2),
        sqrt(1 + ux^2 + uy^2)*(dn_da),
        kappa*ux*sqrt(1 + ux^2 + uy^2),
        kappa*uy*sqrt(1 + ux^2 + uy^2),
        ux/sqrt(1 + ux^2 + uy^2),
        taun*sqrt(1 + ux^2 + uy^2),
        0,
        uy/sqrt(1 + ux^2 + uy^2),
        0,
        taun*sqrt(1 + ux^2 + uy^2)))

    AxL = SMatrix{3,6}((
        ux*(dn_dT),
        0,
        0,
        n,
        (taun*ux^2*(nuyF*ux*uy - nuxF*(1 + uy^2)))/(1 + ux^2 + uy^2),
        (taun*ux*uy*(nuyF*ux*uy - nuxF*(1 + uy^2)))/(1 + ux^2 + uy^2),
        0,
        -((taun*ux^2*(nuyF + nuyF*ux^2 - nuxF*ux*uy))/(1 + ux^2 + uy^2)),
        (taun*ux*uy*(-(nuyF*(1 + ux^2)) + nuxF*ux*uy))/(1 + ux^2 + uy^2),
        ux*(dn_da),
        kappa*(1 + ux^2),
        kappa*ux*uy,
        1,
        taun*ux,
        0,
        0,
        0,
        taun*ux))

    AyL = SMatrix{3,6}((
        uy*(dn_dT),
        0,
        0,
        0,
        (taun*ux*uy*(nuyF*ux*uy - nuxF*(1 + uy^2)))/(1 + ux^2 + uy^2),
        -((taun*uy^2*(nuxF - nuyF*ux*uy + nuxF*uy^2))/(1 + ux^2 + uy^2)),
        n,
        -((taun*ux*uy*(nuyF + nuyF*ux^2 - nuxF*ux*uy))/(1 + ux^2 + uy^2)),
        (taun*uy^2*(-(nuyF*(1 + ux^2)) + nuxF*ux*uy))/(1 + ux^2 + uy^2),
        uy*(dn_da),
        kappa*ux*uy,
        kappa*(1 + uy^2),
        0,
        taun*uy,
        0,
        1,
        0,
        taun*uy))

    srcL = SVector{3}((
        (nuxF*ux + nuyF*uy + n*(1 + ux^2 + uy^2))/(tau*sqrt(1 + ux^2 + uy^2)),
        nuxF,
        nuyF))

    return (AtL, AxL, AyL, srcL)
end
