# ==============================================================================
# HQ_const_BG_consistent.jl — THE THERMODYNAMICALLY CONSISTENT CHARM SECTOR.
#
# NEW FILE (2026-08-23). NOT included by src/Fluidum.jl — nothing shipped
# changes. Drivers load it into the module at runtime:
#
#     Base.include(Fluidum, joinpath(<repo>, "Julia", "Fluidum.jl", "src",
#                                    "Matrix", "HQ_const_BG_consistent.jl"))
#
# and register it as evolution mode :HQ_const_BG_consistent themselves.
#
# WHAT IT IS. The first-moment system for phi = (alpha, nu^r) derived from the
# Delta-projected covariant divergence of the charm energy-momentum tensor of
# the rank-1 Grad / boosted-Juttner state,
#
#     (D_s/T) * Delta^r_nu Cov_mu T_Q^{mu nu} + nu^r = 0,
#     T_Q = epsQ u u + P0 Delta + h (u nu + nu u),   P0 = n T,  epsQ + P0 = n h,
#
# with NO homogeneity step: the shipped derivation (Capellino et al. 2205.07692
# App. D; Tex/HydroFPderivation/FP_Hydro_matching.tex; the notebook
# HQ_on_const_BG_2moment5.0.nb) evaluates the spatial term "in the LRF of a
# homogeneous fluid", which (a) turns d^l P0 = T n0 d^l alpha via a constant-T
# thermodynamic identity, and (b) drops every term generated by gradients of
# the thermodynamic coefficients. Machine-checked in
# Julia/tools/derive_hq_consistent.wls (xAct, the notebook's own conventions):
#
#     consistent row  =  shipped row (kappa -> D_s n01)  +  FIVE terms:
#       (D_s/T)(n + T n10) * Delta^{r mu} d_mu T      [pressure gradient — the
#                                                      full dP0 = n dmu + s dT;
#                                                      the "Hessian" channel]
#       tau_n * n * a^r                               [inertial: (eps+P0) a]
#       tau_n * (nu . grad u)^r                       [shear/vorticity/theta]
#       nu^r * tau_n * (theta_grad + D ln h)          [expansion + the
#                                                      coefficient inside D]
#       nu^r * tau_n * (u^tau/tau + u^r/r)            [GEOMETRIC dilution of the
#                                                      current — in Bjorken this
#                                                      is the exact d(tau nu)=0
#                                                      redshift; gates W0/WB]
#
#     🔴 2026-08-23 CORRECTION: the first derivation missed the geometric term.
#     xCoba's CovD applied to BASIS-indexed CTensor slots drops the
#     Christoffel/sqrt(g) part of a divergence (gate W0 documents it); the
#     abstract-index + BasisExpand route is mandatory. Without the term the
#     current lacks its 1/tau (Bjorken) and u^r/r dilution and is too
#     persistent — visibly over-draining the dilute edge in the linear-D_sT
#     solve.
#
# All four are SOURCE terms (background gradients x fields): A_t and A_x are
# the shipped ones with kappa -> D_s * (dn/dalpha). Gates:
# Tex/MaxEntHydro/diag_hq_consistent_gates.jl (reference points from the .wls,
# plus the tie to the shipped one_d_viscous_matrix_fugacity_BG_only).
#
# CONVENTIONS. Source-on-the-LHS (A_t d_tau phi + A_x d_r phi + src = 0), the
# same as every matrix in this directory; the returned system is divided by
# A_t^{-1} by the caller exactly as in HQ_const_BG.jl. tau_n is the SHIPPED
# tau_diffusion_hadron (Eq. 30 of 2205.07692) — the consistent equation has
# the same relaxation time by construction (tau_n = D_s h/T defines h).
#
# SCOPE. First moment only; unit-charm-charge Boltzmann lists (P0 = nT needs
# Q_c = 1 per species — asserted). Second moments: see the 5-field variant
# below, which keeps the shipped rows 3-5 and is provided so the consistent
# run can carry the passive diagnostics; their sources are NOT corrected here
# (that correction is the divergence-form NS target, measured additively in
# Tex/MaxEntHydro/diag_lp1_deltacm.jl).
# ==============================================================================

"""
    hqc_enthalpy_per_particle(T, α, eos, diffusion)

h = tau_n * T / D_s in GeV — the enthalpy per particle the shipped tau_n
encodes (tau_n = D_s h / T). Uses the same tau_diffusion_hadron / DsT calls as
the production matrices, including HQ_TAUN_SCALE and the HQ_MOMENTUM_DIMS=2
diagnostic branch, so the tie tau_n = D_s h/T is exact under every knob.
"""
function hqc_enthalpy_per_particle(T, α, eos, diffusion)
    taun = τ_diffusion_hadron(T, α, eos, diffusion) * HQ_TAUN_SCALE[]
    if HQ_MOMENTUM_DIMS[] == 2
        z = diffusion.mass / T
        λ1 = z * (z + 1) / (z^2 + 3z + 3)
        taun *= (besselk(2, z) / besselk(3, z)) / λ1
    end
    Ds = DsT(diffusion, T) / T / fmGeV
    return taun * T / Ds, taun, Ds
end

"""
    hqc_matrices(X, tau, r, ur, T, dtT, drT, drur, dtur,
                 n, dn_dT, dn_dmu, taun, Ds, h, hp; consistent = true)

The (alpha, nu^r) system. X = (alpha, nu^r). Returns (At, Ax, source) in the
source-on-the-LHS convention. `consistent = false` reproduces the SHIPPED
first-moment physics (the homogeneous-limit row with kappa = D_s * n) — used
by the gates only; production shipped runs keep using the existing modes.
"""
function hqc_matrices(X, tau, r, ur, T, dtT, drT, drur, dtur,
                      n, dn_dT, dn_dmu, taun, Ds, h, hp; consistent::Bool = true)
    uτ  = sqrt(1 + ur^2)
    ν   = X[2]
    κc  = consistent ? Ds * dn_dmu : Ds * n     # the alpha-drive coefficient

    At = SMatrix{2,2}(
        uτ * dn_dmu,        # (1,1)  d_tau alpha  in row 1
        κc * ur * uτ,       # (2,1)  d_tau alpha  in row 2
        ur / uτ,            # (1,2)  d_tau nu     in row 1
        uτ * taun)          # (2,2)  d_tau nu     in row 2

    Ax = SMatrix{2,2}(
        ur * dn_dmu,        # (1,1)  d_r alpha  in row 1
        κc * uτ^2,          # (2,1)  d_r alpha  in row 2
        1.0,                # (1,2)  d_r nu     in row 1
        ur * taun)          # (2,2)  d_r nu     in row 2

    # row 1: continuity (identical to the shipped rows; the 5-field normalization)
    src1 = n * (drur + dtur * ur / uτ + ur / r + uτ / tau) +
           ν * (1 / r + (ur + ur^3 + dtur * tau) / (uτ^3 * tau)) +
           (drT * ur + dtT * uτ) * dn_dT

    # row 2: the shipped Delta-projection part …
    src2 = ν * (1 - taun * (dtur * ur / uτ + drur * ur^2 / uτ^2))

    if consistent
        # … plus the four derived terms (verbatim from derive_hq_consistent.wls):
        #   pressure-gradient T channel + inertial   (field-independent sources)
        src2 += (Ds / T) * (drur * h * n * ur + dtur * h * n * uτ +
                            dtT * n * ur * uτ + dtT * dn_dT * T * ur * uτ +
                            drT * (n + dn_dT * T) * uτ^2)
        #   nu.grad u + expansion + D ln h           (proportional to nu)
        src2 += (Ds / T) * ν * (2 * drur * h + drT * hp * ur +
                                (2 * dtur * h * ur + dtT * hp * uτ^2) / uτ)
        #   geometric dilution of the current (the W0/WB term)
        src2 += taun * ν * (uτ / tau + ur / r)
    end

    return (At, Ax, SVector{2}(src1, src2))
end

function matrix1d_visc_HQ_BG_consistent!(; dmn_eps = 1e-6, background_fields, α_max = 200.0)
    (A_i, Source, ϕ, tau, X, params) -> matrix1d_visc_HQ_BG_consistent!(
        A_i, Source, ϕ, tau, X, params;
        dmn_eps = dmn_eps, background_fields = background_fields, α_max = α_max)
end

function matrix1d_visc_HQ_BG_consistent!(A_i, Source, ϕ, tau, X, params;
        dmn_eps = 1e-6, background_fields = nothing, α_max = 200.0)

    T, ur, dtT, drT, drur, dtur = background_fields(tau, X[1])

    α_safe = clamp(ϕ[1], -α_max, α_max)

    thermo = thermodynamic(T, α_safe, params.eos.hadron_list)
    n = thermo.pressure                       # the charm-sector density (see charm_HRG.jl)
    dn_dT, dn_dmu = thermo.pressure_derivative
    dn_dmu += dmn_eps

    h, taun, Ds = hqc_enthalpy_per_particle(T, α_safe, params.eos, params.diffusion)
    # dh/dT by central difference through the SAME pipeline (EoS-agnostic; the
    # closed form m K3'/K2' would silently break for multi-species lists)
    δ  = max(1e-4, 1e-3 * T)
    hp = (hqc_enthalpy_per_particle(T + δ, α_safe, params.eos, params.diffusion)[1] -
          hqc_enthalpy_per_particle(T - δ, α_safe, params.eos, params.diffusion)[1]) / (2δ)

    (At, Ax, source) = hqc_matrices(ϕ, tau, X[1], ur, T, dtT, drT, drur, dtur,
                                    n, dn_dT, dn_dmu, taun, Ds, h, hp; consistent = true)

    Ainv = inv(At)
    A_mul_B!(A_i[1], Ainv, Ax)
    jgemvavx!(Source, Ainv, source)
end

# ==============================================================================
# THE 5-FIELD CONSISTENT SYSTEM WITH THE c_M BACK-COUPLING (2026-08-24).
#
# phi = (alpha, nu^r, piQr, piQperp, PiQ). Rows 3-5 are the SHIPPED second-
# moment relaxation (one_d_viscous_matrix_fugacity_BG_only_second_moment,
# called with cM = 0 so its own -- basis-route-derived, hence defective --
# coupling entries never enter). Rows 1-2 are the consistent first moment
# (hqc_matrices) plus the c_M force derived by the ABSTRACT route
# (Julia/tools/derive_hq_cm_coupling.wls, 3/3):
#
#   cM * [ ur*ut*d_tau(zeta) + (1+ur^2)*d_r(zeta) + (drur*ur + dtur*ut)*zeta
#          + (1+ur^2)*(piQr - piQperp)/r + ur*ut*(2 piQr + piQperp)/tau ] ,
#   zeta = piQr + PiQ.
#
# The last two terms -- the HOOP-STRESS divergence and the tau-redshift -- are
# MISSING from the notebook/Fluidum coupling (its basis-indexed CovD drops all
# geometric pieces; gate C0). Production always ran cM = 0, so nothing shipped
# is affected; any future cM != 0 run of the shipped matrix would be.
#
# cM defaults to D_s/T (the physical back-coupling); HQ_CM_BACKREACTION=0
# gives the passive-diagnostic variant (rows 3-5 evolve, nothing feeds back),
# whose (alpha, nu) MUST equal the 2-field consistent solve -- the run-level
# control gate.
# ==============================================================================

"""
    hqc_cm_row2(X, tau, r, ur, dtur, drur, cM) -> (at3, at5, ax3, ax5, src)

The c_M force's row-2 pieces: coefficients of d_tau piQr / d_tau PiQ,
d_r piQr / d_r PiQ, and the source (everything with no field derivative).
piQperp has NO derivative entries (the coupling carries none).
"""
function hqc_cm_row2(X, tau, r, ur, dtur, drur, cM)
    uτ = sqrt(1 + ur^2)
    piQr, piQperp, PiQ = X[3], X[4], X[5]
    ζ = piQr + PiQ
    at = cM * ur * uτ            # coefficient of d_tau piQr AND d_tau PiQ
    ax = cM * uτ^2               # coefficient of d_r  piQr AND d_r  PiQ
    src = cM * ((drur * ur + dtur * uτ) * ζ +
                uτ^2 * (piQr - piQperp) / r +
                ur * uτ * (2 * piQr + piQperp) / tau)
    return at, ax, src
end

function matrix1d_visc_HQ_BG_consistent_5f!(; dmn_eps = 1e-6, background_fields,
                                            α_max = 200.0, use_NR_tauM::Bool = false)
    (A_i, Source, ϕ, tau, X, params) -> matrix1d_visc_HQ_BG_consistent_5f!(
        A_i, Source, ϕ, tau, X, params;
        dmn_eps = dmn_eps, background_fields = background_fields,
        α_max = α_max, use_NR_tauM = use_NR_tauM)
end

function matrix1d_visc_HQ_BG_consistent_5f!(A_i, Source, ϕ, tau, X, params;
        dmn_eps = 1e-6, background_fields = nothing, α_max = 200.0,
        use_NR_tauM::Bool = false)

    T, ur, dtT, drT, drur, dtur = background_fields(tau, X[1])
    α_safe = clamp(ϕ[1], -α_max, α_max)

    thermo = thermodynamic(T, α_safe, params.eos.hadron_list)
    n = thermo.pressure
    dn_dT, dn_dmu = thermo.pressure_derivative
    dn_dmu += dmn_eps

    h, taun, Ds = hqc_enthalpy_per_particle(T, α_safe, params.eos, params.diffusion)
    δ  = max(1e-4, 1e-3 * T)
    hp = (hqc_enthalpy_per_particle(T + δ, α_safe, params.eos, params.diffusion)[1] -
          hqc_enthalpy_per_particle(T - δ, α_safe, params.eos, params.diffusion)[1]) / (2δ)

    # rows 3-5: the shipped relaxation, with ITS cM hard-zeroed (its coupling
    # entries are the defective basis-route ones; ours replace them in row 2)
    z = params.diffusion.mass / T
    kappa = Ds * n
    tauM = use_NR_tauM ? taun / 2 : taun * besselk(4, z) * besselk(2, z) / (2 * besselk(3, z)^2)
    etaM = T * taun / 2
    Ats, Axs, srcs = one_d_viscous_matrix_fugacity_BG_only_second_moment(
        ϕ, tau, X[1], ur, T, dtT, drT, drur, dtur,
        n, dn_dmu, dn_dT, taun, kappa, tauM, etaM, params.diffusion.mass, zero(Ds))

    # rows 1-2: consistent first moment + the correct c_M force
    At2, Ax2, src2 = hqc_matrices(ϕ, tau, X[1], ur, T, dtT, drT, drur, dtur,
                                  n, dn_dT, dn_dmu, taun, Ds, h, hp; consistent = true)
    cM = get(ENV, "HQ_CM_BACKREACTION", "1") == "0" ? zero(Ds) : Ds / T
    # DIAGNOSTIC REGULATOR (documented, scale-separated): the c_M force is not
    # proportional to n, so in the charm-free vacuum tail it drives nu >> n and
    # collapses the implicit integrator's dt on physics that carries no charm.
    # Damp it by n/(n + n_floor) with n_floor (HQC_CM_NFLOOR, default 1e-6)
    # ~three orders below n_fo ~ 8e-4: at the freeze-out surface the
    # suppression is < 0.2% and every diagnostic here reads the surface.
    nfloor = parse(Float64, get(ENV, "HQC_CM_NFLOOR", "1e-6"))
    cM *= n / (n + nfloor)
    at3, ax3, csrc = hqc_cm_row2(ϕ, tau, X[1], ur, dtur, drur, cM)

    At = MMatrix{5,5,Float64}(Ats); Ax = MMatrix{5,5,Float64}(Axs)
    src = MVector{5,Float64}(srcs)
    At[1, 1] = At2[1, 1]; At[1, 2] = At2[1, 2]; At[1, 3] = 0.0; At[1, 4] = 0.0; At[1, 5] = 0.0
    At[2, 1] = At2[2, 1]; At[2, 2] = At2[2, 2]; At[2, 3] = at3; At[2, 4] = 0.0; At[2, 5] = at3
    Ax[1, 1] = Ax2[1, 1]; Ax[1, 2] = Ax2[1, 2]; Ax[1, 3] = 0.0; Ax[1, 4] = 0.0; Ax[1, 5] = 0.0
    Ax[2, 1] = Ax2[2, 1]; Ax[2, 2] = Ax2[2, 2]; Ax[2, 3] = ax3; Ax[2, 4] = 0.0; Ax[2, 5] = ax3
    src[1] = src2[1]
    src[2] = src2[2] + csrc

    Ainv = inv(SMatrix{5,5}(At))
    A_mul_B!(A_i[1], Ainv, SMatrix{5,5}(Ax))
    jgemvavx!(Source, Ainv, SVector{5}(src))
end
